spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgresql://notification-db:5432/notification
  flyway:
    url: jdbc:postgresql://notification-db:5432/notification
    locations: classpath:db/migration
graphql:
  packages: org.misarch.notification
  federation:
    enabled: true